server:
  port: 8084

spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/credithub
    username: credithub
    password: credithub
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      observation-enabled: true   # lê o traceparent do header e continua o trace da request original
    consumer:
      group-id: audit-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

management:
  tracing:
    sampling:
      probability: 1.0 # Em produção seria 1-10%
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health,prometheus
